services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: ruuvi-mosquitto
    env_file: .env.docker
    restart: unless-stopped
    ports:
      - "8883:8883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./config/acl:/mosquitto/config/acl:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
      - certs:/mosquitto/config/certs:ro
      - ca_certs:/mosquitto/config/ca_certificates:ro
      - passwd:/mosquitto/config/passwd:ro
    networks:
      - ruuvi-network
    healthcheck:
      test:
        [
          "CMD",
          "mosquitto_pub",
          "-h",
          "localhost",
          "-p",
          "8883",
          "-t",
          "health",
          "-m",
          "check",
          "--cafile",
          "/mosquitto/config/ca_certificates/ca.crt",
          "-u",
          "ruuvi",
          "-P",
          "$$MQTT_PASS",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - MQTT_PASS=${MQTT_PASS}

  ruuvi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ruuvi-home
    env_file: .env.docker
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
      - certs:/app/certs:ro
    networks:
      - ruuvi-network
    depends_on:
      mosquitto:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - MQTT_HOST=mosquitto
      - MQTT_PORT=8883
      - MQTT_USER=ruuvi
      - MQTT_PASS=${MQTT_PASS}
      - SERVER_IP=${SERVER_IP:-0.0.0.0}
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:3000/manifest.json"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ruuvi-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  mosquitto_data:
    driver: local
  mosquitto_logs:
    driver: local
  app_data:
    driver: local
  app_logs:
    driver: local
  certs:
    driver: local
  ca_certs:
    driver: local
  passwd:
    driver: local
