services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: ruuvi-mosquitto
    env_file: .env.docker
    restart: unless-stopped
    ports:
      - "8883:8883"
    volumes:
      - ./config/mosquitto-docker.conf:/mosquitto/config/mosquitto.conf:ro
      - ./config/acl:/mosquitto/config/acl:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
      - mosquitto_certs:/mosquitto/config/certs
      - mosquitto_ca:/mosquitto/config/ca_certificates
      - mosquitto_passwd:/mosquitto/config/passwd
      - mosquitto_run:/var/run/mosquitto
    networks:
      - ruuvi-network

    healthcheck:
      test: ["CMD-SHELL", "mosquitto_pub -h localhost -p 1883 -t health -m check || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - MQTT_PASS=${MQTT_PASS}

  ruuvi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ruuvi-home
    env_file: .env.docker
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
      - web_certs:/app/certs
    networks:
      - ruuvi-network
    depends_on:
      mosquitto:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - MQTT_HOST=mosquitto
      - MQTT_PORT=8883
      - MQTT_USER=ruuvi
      - MQTT_PASS=${MQTT_PASS}
      - SERVER_IP=${SERVER_IP:-0.0.0.0}
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:3000/manifest.json"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ruuvi-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  mosquitto_data:
    driver: local
  mosquitto_logs:
    driver: local
  mosquitto_certs:
    driver: local
  mosquitto_ca:
    driver: local
  mosquitto_passwd:
    driver: local
  mosquitto_run:
    driver: local
  app_data:
    driver: local
  app_logs:
    driver: local
  web_certs:
    driver: local
